In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
## Introduction to Numpy
"""
numerical python library => Used for Scientific Computing, Data analysis, and numerical Computing Tasks.
Data Structures
List => [] -> Contains Heterogeneous Data
array => In numpy an array is an fundamental object - > used to store homogeneous data
array vs List
- In array Same data types elements || In list different types of data types can be stored stored.
- the array elements are stored in Contigeous Memory location || List is not stored in contigeous memory location
- arrays are static and cannot be resized || List can be resized
- array takes less space in memory || List takes more space in the memory

"""

In [ ]:
# 1D (1 dimentional array)
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
l1 = [1,2,3]
l2 = [4,5,6]

In [ ]:
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
print(arr1 + arr2)

[5 7 9]


In [ ]:
# 2D array

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D array

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]]


In [ ]:
## Array Attributes : In attributes we dont have parenthesis
'''
- shape : Gives the dimention of the array
'''
print(arr1.shape)
#The out put indicates that arr1 is a 1D array with 3 elements
#The shape (3,) tells that there is only 1 dimention with length of 3.


(3,)


In [ ]:
print(arr3.shape)
## The output indicates that

(1, 2, 3)


In [ ]:
# Size : Total number of elements
print(arr3.size)

6


In [ ]:
# ndim : number of array dimentions
arr3 = np.array([[[1,2,3],[4,5,6]]])
print(arr3.ndim)
#This was 3 dimentional array do 3

3


In [ ]:
# dtype : Gives the data of the array
print(arr3.dtype)


int64


In [ ]:

#Accessing elements in array
print(arr3[0,1])

[4 5 6]


In [ ]:
##Slicing
print(arr2[:1])

[[1 2 3]]


In [ ]:
##Numpy array operations

In [ ]:
# Element wise operations
arr = np.array([4,7,9])
print(arr + 10)

[14 17 19]


In [ ]:
print(arr * 10)

[40 70 90]


In [ ]:
## used if that specific operation is to be applied to all the elements in the array


In [ ]:
## Matrix operations
A = np.array([[1,2],[5,8]])
B = np.array([[2,3],[2,9]])

#Numpy allows matrix multiplication, Transpose
print(np.dot(A,B))

[[ 6 21]
 [26 87]]


In [ ]:
# Matrix Transpose
print(A.T)

[[1 5]
 [2 8]]


In [ ]:
# Common numpy functions
# arrange : Similar to python's range, but returns an array
print(np.arange(1,10,2))
#it gives same output as for loop range but in array

[1 3 5 7 9]


In [ ]:
# linespace: Generates a specified number of evenly spaced values over an interval
print(np.linspace(0,1,5))
#Generates sequence of number (start, end, number of elements)


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Reshape : the reshape function changes the shpae of an array without changing its data
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr.reshape(2,5))


[[1 2 3 4 5]
 [6 7 8 9 0]]


In [ ]:
## aggregate functions : sum, min, max, mean, etc
arr = np.array([1,2,3,4,5,6,7,8,9,0])
arr.sum()

45

In [ ]:
arr.min()

0

In [ ]:
arr.mean()

4.5

In [ ]:
print(np.median(arr))

4.5


In [ ]:
#In numpy we dont have attribute for mode
#We import external library
from scipy import stats
print(stats.mode(arr))

ModeResult(mode=0, count=1)


In [ ]:
## Beoadcasting
#Numpy broadcasting allows for arithmetic operations on arrays of different shapes and sizes,
#where one arrays dimensions are adjusted to match the others

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1],[2],[3]])
print(arr1+arr2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
# Random number with NumPy
print(np.random.randint(0,10,size = (3,3)))  #Size -> number of rows and columns

[[1 8 3]
 [7 5 7]
 [0 5 4]]


In [ ]:
print(np.random.rand(3,3))

[[0.75770191 0.48983614 0.98226705]
 [0.27336746 0.49677722 0.9144005 ]
 [0.97984107 0.48633057 0.85884217]]


In [ ]:
print(np.random.randn(3,3))

[[-1.09127991  0.71405236  0.80518023]
 [ 0.23459422 -1.12443456  0.62654772]
 [ 0.42401996  0.25456706 -0.17032511]]
